# Generated by Django 5.0.6 on 2024-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
